### ISSUE TITLE
missing files ? 

### ISSUE THREAD

**Issue by waminos** [pswpswpsw/paper-nif#1]
Hi,
Im trying to replicate your work, but cant find inside sec_3_6_Sparse_Sensing_SST:
 get_normalized_data.py  / qdeim.py /  run_nif_txy_siren_sst_autoencoder.py
Is it planned to be commited sometime soon ?
Thanks

**Comment by pswpswpsw** [comment]
Good question! I apologize for accidently put them in those pre-existing runs in the [Google Drive](
https://drive.google.com/drive/u/1/folders/1CfMUKBfuo92BN_qIWbNxzfLoxRradFRw). Just download `sec_3_6_data_runs.zip`. 

You can also find the link in the `README` file of this project, just a bit above the `Reproducing the results`

**Comment by waminos** [comment]
Thanks Pan
